defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: yjk

test:
  <<: *defaults
  database: safe_eats_pdx_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: safe_eats_pdx
  uri: <%= ENV['MONGODB_URI'] %>
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
